
DROP USER IF EXISTS 'khaki'@'localhost';
create user 'khaki'@'localhost' identified by 'password';
GRANT DELETE ON plungercat.* TO 'khaki'@'localhost';
GRANT INSERT ON plungercat.* TO 'khaki'@'localhost';
GRANT SELECT ON plungercat.* TO 'khaki'@'localhost';
GRANT UPDATE ON plungercat.* TO 'khaki'@'localhost';

DROP DATABASE IF EXISTS plungercat;
CREATE DATABASE plungercat;
USE plungercat;

CREATE TABLE RESTAURANTS
(
    R_ID varchar(1024) NOT NULL UNIQUE,
    R_NAME varchar(2014) NOT NULL,
    PRIMARY KEY(R_ID)
);

CREATE TABLE USERS
(
    U_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    U_EMAIL varchar(1024) NOT NULL UNIQUE,
    U_PASSWORD varchar(1024) NOT NULL,
    U_FIRST_NAME varchar(1024) NOT NULL,
    U_LAST_NAME varchar(1024) NOT NULL,
    U_GENDER varchar(15) NOT NULL,
    PRIMARY KEY(U_ID)
);

CREATE TABLE FAVORITES
(
    U_ID INT NOT NULL,
    R_ID varchar(1024) NOT NULL,
    PRIMARY KEY(U_ID, R_ID),
    FOREIGN KEY(U_ID) REFERENCES USERS(U_ID),
    FOREIGN KEY(R_ID) REFERENCES RESTAURANTS(R_ID)
);

CREATE TABLE HISTORY
(
    U_ID INT NOT NULL,
    R_ID varchar(1024) NOT NULL,
    H_DATE DATETIME NOT NULL,
    PRIMARY KEY(U_ID, R_ID),
    FOREIGN KEY(U_ID) REFERENCES USERS(U_ID),
    FOREIGN KEY(R_ID) REFERENCES RESTAURANTS(R_ID)
);

INSERT INTO RESTAURANTS (R_ID, R_NAME) VALUES ('dovujn6osuLTfytLf5eDGw', 'Cozmos Cafe + Bistro');
INSERT INTO RESTAURANTS (R_ID, R_NAME) VALUES ('tc4LQ_GQGt8qLdFKH2qNVQ', 'Hakkaku Ramen');

INSERT INTO USERS (U_EMAIL, U_PASSWORD, U_FIRST_NAME, U_LAST_NAME, U_GENDER) VALUES ('dog', 'dog', 'dog', 'dog', 'dog');
INSERT INTO USERS (U_EMAIL, U_PASSWORD, U_FIRST_NAME, U_LAST_NAME, U_GENDER) VALUES ('cat', 'cat', 'cat', 'cat', 'cat');

INSERT INTO FAVORITES (U_ID, R_ID) VALUES (1, 'dovujn6osuLTfytLf5eDGw');
INSERT INTO FAVORITES (U_ID, R_ID) VALUES (2, 'dovujn6osuLTfytLf5eDGw');
INSERT INTO FAVORITES (U_ID, R_ID) VALUES (2, 'tc4LQ_GQGt8qLdFKH2qNVQ');
